# Generated by Django 5.0 on 2023-12-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lecture_app", "0003_alter_theory_options_and_more"),
        ("tags_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="theory",
            name="tags",
            field=models.ManyToManyField(to="tags_app.tag"),
        ),
    ]
