# Generated by Django 5.0 on 2023-12-17 16:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="codetask",
            options={
                "verbose_name": "Условие задачи",
                "verbose_name_plural": "Условия задач",
            },
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"verbose_name": "Задача", "verbose_name_plural": "Задачи"},
        ),
        migrations.AlterModelOptions(
            name="tasktype",
            options={
                "verbose_name": "Тип задания",
                "verbose_name_plural": "Типы заданий",
            },
        ),
        migrations.AlterModelOptions(
            name="testcase",
            options={
                "verbose_name": "Тест для задачи",
                "verbose_name_plural": "Тесты для задач",
            },
        ),
    ]
