# Generated by Django 5.0 on 2023-12-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags_app", "0001_initial"),
        ("task_app", "0002_alter_codetask_options_alter_task_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(to="tags_app.tag"),
        ),
    ]
