# Generated by Django 5.0 on 2024-01-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_app", "0003_task_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testcase",
            name="content",
        ),
        migrations.AddField(
            model_name="testcase",
            name="stdin",
            field=models.FileField(
                default=1, upload_to="", verbose_name="Входные данные"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="testcase",
            name="stdout",
            field=models.FileField(
                default=1, upload_to="", verbose_name="Выходные данные"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="task",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
