# Generated by Django 5.0 on 2024-01-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_app", "0004_remove_testcase_content_testcase_stdin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testcase",
            name="stdin",
            field=models.FileField(
                null=True, upload_to="", verbose_name="Входные данные"
            ),
        ),
    ]
