# Generated by Django 5.0 on 2023-12-17 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("task_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("python", "java"),
                            ("java", "java"),
                            ("C++", "C++"),
                            ("PHP", "PHP"),
                            ("C", "C"),
                            ("js", "js"),
                        ],
                        max_length=64,
                        verbose_name="Язык программирования",
                    ),
                ),
                ("code", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Ожидание"),
                            ("SUCCESS", "Успех"),
                            ("ERROR", "Ошибка"),
                        ],
                        default="PENDING",
                        max_length=64,
                        verbose_name="Тип пользователя",
                    ),
                ),
                (
                    "worker_uuid",
                    models.CharField(max_length=1024, verbose_name="Номер задачи"),
                ),
                (
                    "code_task",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissions",
                        to="task_app.codetask",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
