# Generated by Django 5.0 on 2024-01-08 22:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submission_app", "0003_submission_output_alter_submission_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="worker_uuid",
        ),
    ]
