# Generated by Django 5.0 on 2024-02-24 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submission_app", "0004_remove_submission_worker_uuid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hint_type",
                    models.CharField(
                        choices=[
                            ("after_run", "до тестирования"),
                            ("before_run", "после тестирования"),
                        ],
                        default="after_run",
                        max_length=64,
                    ),
                ),
                (
                    "content",
                    models.JSONField(blank=True, null=True, verbose_name="Контент"),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="submission_app.submission",
                        verbose_name="Результат тестирования",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
    ]
